x-gpu-x11-ros-devices: &gpu-x11-ros-devices
  devices:
    - /dev/shm:/dev/shm  # ros
    - /dev/dri:/dev/dri  # gpu, x11
    - /dev/vc-mem:/dev/vc-mem  # gpu
    - /dev/vcio:/dev/vcio  # gpu

# if the service does not need ros shared memory transport, otherwise
# same as gpu-x11-ros-devices
x-gpu-x11-devices: &gpu-x11-devices
  devices:
    - /dev/dri:/dev/dri  # gpu, x11
    - /dev/vc-mem:/dev/vc-mem  # gpu
    - /dev/vcio:/dev/vcio  # gpu

services:
  gisnav:
    <<: *gpu-x11-ros-devices

  px4:
    <<: *gpu-x11-devices

  ardupilot:
    <<: *gpu-x11-devices

  qgc:
    <<: *gpu-x11-devices

  qgis:
    <<: *gpu-x11-devices

  rviz:
    <<: *gpu-x11-ros-devices
