x-arm64: &arm64
  build:
    platforms:
      - linux/arm64

services:
  # User arm64 version of mapserver docker image (e.g. for Jetson Nano)
  mapserver:
    <<: *arm64
    build:
      args:
        DOCKER_TAG: latest-arm64

  micro-ros-agent:
    <<: *arm64

  mavros:
    <<: *arm64

  gisnav:
    <<: *arm64
