map_nav_node:
  ros__parameters:
    wms:
      url: 'http://localhost:8080/wms'
      version: '1.1.1'
      layer: 'Imagery'
      srs: 'EPSG:4326'  # util.get_bbox currently only supports EPSG:4326 --> don't change this setting
      request_timeout: 5
    misc:
      affine_threshold: 5
      gimbal_projection: True
      max_map_radius: 1000
      map_radius_meters_default: 400
      update_map_center_threshold: 50
      update_map_radius_threshold: 50
      publish_frequency: 40  # Hz
      export_position: True
    map_update:
      initial_guess:  # Values from ksql_airport.world file
        lat: 37.523640
        lon: -122.255122
      update_frequency: 1
      default_altitude: 130
  superglue:  # Recommended outdoor config from SuperGlue repo's README.md
    superpoint:
      nms_radius: 3
      keypoint_threshold: 0.005
      max_keypoints: 2048
    superglue:
      weights: 'outdoor'
      sinkhorn_iterations: 20
      match_threshold: 0.2